name: GHA

run-name: ${{ github.head_ref || github.ref_name }}-gdlint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  gdlint:
    name: Formatting Checks
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 5

    steps:
      - name: Checkout GdUnit Repository
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: "Setup GDLint"
        uses: Scony/godot-gdscript-toolkit@master
        with:
          version: 4.5.0

      - name: "Run GDLint"
        id: run-gdlint
        shell: bash
        run: |
          mkdir -p reports/gdlint/
          gdlint addons/gaea/editor/ | tee reports/gdlint/editor.txt
          gdlint addons/gaea/graph/ | tee reports/gdlint/graph.txt
          gdlint addons/gaea/nodes/ | tee reports/gdlint/nodes.txt
          gdlint addons/gaea/resources/ | tee reports/gdlint/resources.txt

      - name: "Upload GDLint Report"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gdlint.txt
          path: reports/gdlint/**
          if-no-files-found: error
          compression-level: 0 # no compression
